title: John Leonard # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>
  Data Scientist / Business Analyst with 2+ years of professional experience; passionate about statistics, data visualization and environmental sustainability. 
  <br>
  Previously at MIS Insurance, and RSM US (Risk Consulting).
  <br>
  Degrees in Management Information Systems, Risk Management & Insurance, and a minor in Computer Science from Florida State University.
  <br><br>
  <a href="https://www.linkedin.com/in/johnleonard512/">View my LinkedIn Profile</a> 
  <br><br>
  <a href ="http://johnleonard512.pythonanywhere.com/"> View my Python Web App</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'

